export const CHANGE_TOOL_SIZE = 'CHANGE_TOOL_SIZE';
export const CHANGE_TOOL = 'CHANGE_TOOL';
export const CHANGE_CANVAS_SIZE = 'CHANGE_CANVAS_SIZE';
export const CHANGE_FIRST_CANVAS_COLOR = 'CHANGE_FIRST_CANVAS_COLOR';
export const CHANGE_SECOND_CANVAS_COLOR = 'CHANGE_SECOND_CANVAS_COLOR';
