export const MAP_IMAGE_DATA_TO_STATE = 'MAP_IMAGE_DATA_TO_STATE';
export const ADD_NEW_CANVAS_FRAME = 'ADD_NEW_CANVAS_FRAME';
export const CHANGE_ACTIVE_CANVAS_FRAME = 'CHANGE_ACTIVE_CANVAS_FRAME';
export const DELETE_ALL_ADDED_CANVAS_FRAMES = 'DELETE_ALL_ADDED_CANVAS_FRAMES';
export const DELETE_CANVAS_FRAME = 'DELETE_CANVAS_FRAME';
export const ADD_DUPLICATE_CANVAS_FRAME = 'ADD_DUPLICATE_CANVAS_FRAME';
